FROM tdmproject/tdmqc
ENV DPC_HOME /opt/dpc

COPY dpc $DPC_HOME
WORKDIR $DPC_HOME

RUN pip3 install tifffile clize dateparser

ENTRYPOINT ["/entrypoint.sh", "fake_user.sh", "python3", "setup_source.py"]
