FROM crs4/pydoop-client:latest
# LABEL maintainer="gianluigi.zanetti@crs4.it"


RUN yum install \
        openssl-devel \
        which \
        unzip \
        wget

RUN wget https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz && \
    tar xvf cmake-3.3.2-Linux-x86_64.tar.gz   && \
    cp -R cmake-3.3.2-Linux-x86_64/bin /usr/  && \
    cp -R cmake-3.3.2-Linux-x86_64/doc /usr/  && \   
    cp -R cmake-3.3.2-Linux-x86_64/man /usr/  && \    
    cp -R cmake-3.3.2-Linux-x86_64/share /usr/  && \
    rm cmake-3.3.2-Linux-x86_64.tar.gz  && \
    rm -rf cmake-3.3.2-Linux-x86_64

RUN wget https://github.com/TileDB-Inc/TileDB/archive/1.4.1.tar.gz && \
    tar xvf 1.4.1.tar.gz && \
    rm 1.4.1.tar.gz && \
    cd TileDB-1.4.1/ && \
    mkdir build && \
    cd build && \
    ../bootstrap --prefix=/usr --enable-hdfs && \
    make  && \
    make install-tiledb && \
    cd ..

RUN pip3 install --upgrade pip && \
    pip3 install tiledb

RUN ldconfig /opt/hadoop/lib/native && \
    ldconfig /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-1.el7_6.x86_64/jre/lib/amd64/server && \
    CLASSPATH=`/opt/hadoop/bin/hadoop classpath --glob` && \
    echo "export CLASSPATH=\"${CLASSPATH}\"" >> /etc/profile.d/hadoop.sh

RUN useradd -m jupyter && \
    pip install --no-cache-dir \
        wget \
        ckanapi \
        jupyter \
        matplotlib


#WORKDIR /home/jupyter
#USER jupyter
#RUN mkdir .jupyter notebooks
#COPY --chown=jupyter jupyter_notebook_config.py .jupyter/

#WORKDIR notebooks

#EXPOSE 8888
ENTRYPOINT ["/bin/bash", "-c", "sleep 99999"]
