FROM python:3.7

ARG PIP_BIN=pip3
ENV PIP=$PIP_BIN

RUN $PIP install --no-cache-dir --upgrade pip

ENV TDMQ_DIST=/tdmq-dist
ENV DATA_DIR="${TDMQ_DIST}/data"

EXPOSE 8000
CMD /web-entrypoint.sh

COPY --chown=root ./tdmq-dist/tdmq/requirements-server.txt "${TDMQ_DIST}/tdmq/"
RUN $PIP install -r "${TDMQ_DIST}/tdmq/requirements-server.txt"

COPY --chown=root ./tdmq-dist "${TDMQ_DIST}"
COPY --chown=root web-entrypoint.sh /

RUN chmod a+rx /web-entrypoint.sh \
 && cd "${TDMQ_DIST}" \
 && find . -type f -print0 | xargs -0 chmod a+r \
 && find . -type d -print0 | xargs -0 chmod a+rx \
 && $PIP install .

WORKDIR "${TDMQ_DIST}/tdmq"
