FROM python:3.7
COPY ./tdmq-dist /tdmq-dist
WORKDIR /tdmq-dist
RUN pip install --upgrade pip
RUN pip install flask gunicorn pytest sphinx sphinxcontrib-httpdomain
RUN pip install -e .
EXPOSE 8000
WORKDIR /tdmq-dist/tdmq
CMD ["gunicorn", "-b", "0.0.0.0:8000", "wsgi:app"]
