FROM python:3.7

RUN pip install --upgrade pip

ENV TDMQ_DIST=/tdmq-dist
ENV DATA_DIR="${TDMQ_DIST}/data"


EXPOSE 8000
CMD /web-entrypoint.sh

COPY --chown=root ./tdmq-dist "${TDMQ_DIST}"
COPY --chown=root web-entrypoint.sh /

RUN chmod a+rx /web-entrypoint.sh \
 && cd "${TDMQ_DIST}" \
 && find . -type f -print0 | xargs -0 chmod a+r \
 && find . -type d -print0 | xargs -0 chmod a+rx \
 && pip install -e .

WORKDIR "${TDMQ_DIST}/tdmq"
