#!/bin/bash

set -euo pipefail
[ -n "${DEBUG:-}" ] && set -x
this="${BASH_SOURCE-$0}"
this_dir=$(cd -P -- "$(dirname -- "${this}")" && pwd -P)

pushd "${this_dir}"
cid=$(docker-compose ps -q web)
if [ -z "${cid:-}" ]; then
    echo 'ERROR: service "web" is not running' 1>&2
    exit 1
fi
docker cp ../tests ${cid}:/
docker-compose exec web bash -c 'sed -i -e "s/localhost/timescaledb/" /tests/conftest.py'
docker-compose exec timescaledb bash -c 'i=0; until pg_isready || [ ${i} -ge 2 ] ; do sleep 1; ((++i)); done'
docker-compose exec web bash -c 'pytest /tests'
docker-compose exec web bash -c 'make -C /tdmq-dist/apidocs html'
popd
